### ISSUE TITLE
如何使用discord指令？

### ISSUE THREAD

**Issue by Tyoviry** [watagashi-uni/Unibot#10]
你好，我把機械人加在自己的私人server，但 / 指令並沒有反應
請問是bug 還是在discord是使用其他符號
而且只輸入指令本身也沒反應
謝謝

**Comment by watagashi-uni** [comment]
我刚刚试了bot是好的 而且不管加不加斜杠都可以反应 是不是添加机器人的时候没有给发送消息的权限或者机器人的身份组不能发消息？

**Comment by Tyoviry** [comment]
抱歉 已經正常運作了 是機械人身份組的問題 謝謝
