### ISSUE TITLE
大佬有想法做Discord的bot吗？

### ISSUE THREAD

**Issue by nenesekai** [watagashi-uni/Unibot#6]

**Comment by nenesekai** [comment]
我有想法想写一个 但是不知道能不能调用你的unibot api

**Comment by watagashi-uni** [comment]
想过做 dcbot 但是自己玩的少dc上认识的人也很少就没做了，要做的话也不是不行
如果你想做的话 api.unipjsk.com 的查数据的 api 可以用

**Comment by nenesekai** [comment]
> 想过做 dcbot 但是自己玩的少dc上认识的人也很少就没做了，要做的话也不是不行 如果你想做的话 api.unipjsk.com 的查数据的 api 可以用

好的，现在已经开始动手写了。我会参考你unibot的代码去一个个功能实现，但是不会直接复制粘贴。

**Comment by Asiimoviet** [comment]
api.unipjsk.com上边查别名的两个接口好像都用不了：getsongid还有getalias2

会返回一个internal server error

**Comment by nenesekai** [comment]
> > 想过做 dcbot 但是自己玩的少dc上认识的人也很少就没做了，要做的话也不是不行 如果你想做的话 api.unipjsk.com 的查数据的 api 可以用
> 
> 好的，现在已经开始动手写了。我会参考你unibot的代码去一个个功能实现，但是不会直接复制粘贴。

好吧 能不能直接用你画profile和b30的设计和代码呢？ @watagashi-uni

**Comment by nenesekai** [comment]
顺便放一个项目地址 https://github.com/asiimoviet/nenerobot

**Comment by watagashi-uni** [comment]
> > > 想过做 dcbot 但是自己玩的少dc上认识的人也很少就没做了，要做的话也不是不行 如果你想做的话 api.unipjsk.com 的查数据的 api 可以用
> > 
> > 
> > 好的，现在已经开始动手写了。我会参考你unibot的代码去一个个功能实现，但是不会直接复制粘贴。
> 
> 好吧 能不能直接用你画profile和b30的设计和代码呢？ @watagashi-uni

随便用 我用的MIT协议

**Comment by watagashi-uni** [comment]
我把我分布式客户端的代码改了下就可以在dc用了 移植没啥问题

**Comment by watagashi-uni** [comment]
![dcbot](https://assets.unipjsk.com/pics/dcbot.jpg)

**Comment by nenesekai** [comment]
还有就是unibots的api查profile有开放除了日服以外的服务器吗现在

**Comment by watagashi-uni** [comment]
> 还有就是unibots的api查profile有开放除了日服以外的服务器吗现在

不公开开放，要是想用可以私聊
另外可以试试我部署的dcbot：https://discord.com/api/oauth2/authorize?client_id=975690393339457547&permissions=8&scope=bot

**Comment by nenesekai** [comment]
牛哇 加个qq呗 982021702
